SysIMiBio/core/urls.py
from django.urls import path, include
from SysIMiBio.core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('accounts/login', include('django.contrib.auth.urls'), name='Login'),
    path('accounts/logout', include('django.contrib.auth.urls'), name='Logout'),
]

SysIMiBio/imibio/urls.py
from django.urls import path, include
from SysIMiBio.imibio import views as v

app_name = 'imibio'

urlpatterns = [
    path('', v.imibio_occs_list, name='imibio_occs_list'),
    path('detalles/<int:pk>/', v.Imibio_occ_detail, name='imibio_occ_detail'),
    path('agregar', v.agregar_occurencia, name='agregar_occurencia'),
    #path('mapaSNDB/', v.occs_map, name='occs_mapSNDB'),
    #path('geojson/', v.occs_geojson, name='occs_geojson'),
    #path('occsList/', v.occs, name='occsList'),
]

SysIMiBio/sndb/urls.py
from django.urls import path
from SysIMiBio.sndb import views as v

app_name = 'sndb'

urlpatterns = [
    path('', v.occs_list, name='occs_list'),
    path('<int:pk>', v.occ_detail, name='occ_detail'),
    path('mapaSNDB/', v.occs_map, name='occs_mapSNDB'),
    path('geojson/', v.occs_geojson, name='occs_geojson'),
    path('occslist.js/', v.occs, name='occsList'),
]

SysIMiBio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('SysIMiBio.core.urls'), name='home'),
    path('accounts/', include('accounts.urls')),  # https://learndjango.com/tutorials/django-signup-tutorial
    path('accounts/', include('django.contrib.auth.urls')),
    path('sndb/', include('SysIMiBio.sndb.urls')),
    path('admin/', admin.site.urls),
    path('imibio/', include('SysIMiBio.imibio.urls')),
]

accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

SysIMiBio/core/models.py
from django.db import models

class TimeStampedModel(models.Model):
    created = models.DateTimeField('Creado en', auto_now_add = True, auto_now = False),
    modified = models.DateTimeField('Alterado en', auto_now_add = False, auto_now = True)

    class Meta:
        abstract = True

SysIMiBio/core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

SysIMiBio/core/templates/includes/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <span class="navbar-brand disabled">IMiBio</span>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <li class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:index' %}"> Início <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Datos SNDB</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'sndb:occs_list' %}">
                        <i class="fa fa-pagelines"></i> Lista ocurrencias</a>
                    <a class="dropdown-item" href="{% url 'sndb:occs_mapSNDB' %}">
                        <i class="fa fa-globe"></i> Mapa ocurrencias</a>
                    <a class="dropdown-item disabled" href="#">
                        <i class="fa fa-bar-chart"></i> Estadísticas</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Datos IMiBio</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'imibio:agregar_occurencia' %}"> Agregar ocurencia</a>
                    <a class="dropdown-item" href="{% url 'imibio:imibio_occs_list' %}"> Lista Ocurrencias</a>
                    <a class="dropdown-item disabled" href="#">Mapa Ocurrencias</a>
                    <a class="dropdown-item disabled" href="#">Estadísticas</a>
                </div>
            </li>
        </ul>
        <!--<form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </for\m>-->
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}

            {% if user.is_superuser %}
                  <li class="nav-item">
                    <a role="button" class="btn btn-warning" href="{% url 'signup' %}"> Crear usuario </a>
                  </li>
                  <li class="nav-item">' '</li>

                {% endif %}

            <li class="nav-item">
                <a role="button" class="btn btn-danger" href="{% url 'logout' %}">
                    <span></span><span class="fa fa-sign-in"></span> Salir </a>
            </li>



            {% else %}
            <li class="nav-item">
                <a  role="button" class="btn navbar-btn btn-success" href="{% url 'login' %}">
                    <span class="fa fa-user"></span> Login </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>