SysIMiBio/sndb/urls.py
from django.urls import path
from SysIMiBio.sndb import views as v

app_name = 'sndb'

urlpatterns = [
    path('', v.occs_list, name='occs_list'),
    path('<int:pk>', v.occ_detail, name='occ_detail'),
    path('mapaSNDB/', v.occs_map, name='occs_mapSNDB'),
    path('geojson/', v.occs_geojson, name='occs_geojson'),
    path('occslist.js/', v.occs, name='occsList'),
]

SysIMiBio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('SysIMiBio.core.urls'), name='home'),
    path('accounts/', include('accounts.urls')),  # https://learndjango.com/tutorials/django-signup-tutorial
    path('accounts/', include('django.contrib.auth.urls')),
    path('sndb/', include('SysIMiBio.sndb.urls')),
    path('admin/', admin.site.urls),
    path('imibio/', include('SysIMiBio.imibio.urls')),
]

accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

SysIMiBio/sndb/models.py
from django.conf import settings
from django.contrib.gis.db import models
from django.urls import reverse_lazy


class Occurrences(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    gbifID = models.BigIntegerField(blank=True, null=True)
    abstract = models.TextField(blank=True, null=True)
    accessRights = models.TextField(blank=True, null=True)
    accrualMethod = models.TextField(blank=True, null=True)
    accrualPeriodicity = models.TextField(blank=True, null=True)
    accrualPolicy = models.TextField(blank=True, null=True)
    alternative = models.TextField(blank=True, null=True)
    audience = models.TextField(blank=True, null=True)
    available = models.TextField(blank=True, null=True)
    bibliographicCitation = models.TextField(blank=True, null=True)
    conformsTo = models.TextField(blank=True, null=True)
    contributor = models.TextField(blank=True, null=True)
    coverage = models.TextField(blank=True, null=True)
    created = models.TextField(blank=True, null=True)
    creator = models.TextField(blank=True, null=True)
    date = models.TextField(blank=True, null=True)
    dateAccepted = models.TextField(blank=True, null=True)
    dateCopyrighted = models.TextField(blank=True, null=True)
    dateSubmitted = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    educationLevel = models.TextField(blank=True, null=True)
    extent = models.TextField(blank=True, null=True)
    format = models.TextField(blank=True, null=True)
    hasFormat = models.TextField(blank=True, null=True)
    hasPart = models.TextField(blank=True, null=True)
    hasVersion = models.TextField(blank=True, null=True)
    identifier = models.TextField(blank=True, null=True)
    instructionalMethod = models.TextField(blank=True, null=True)
    isFormatOf = models.TextField(blank=True, null=True)
    isPartOf = models.TextField(blank=True, null=True)
    isReferencedBy = models.TextField(blank=True, null=True)
    isReplacedBy = models.TextField(blank=True, null=True)
    isRequiredBy = models.TextField(blank=True, null=True)
    isVersionOf = models.TextField(blank=True, null=True)
    issued = models.TextField(blank=True, null=True)
    language = models.TextField(blank=True, null=True)
    license = models.TextField(blank=True, null=True)
    mediator = models.TextField(blank=True, null=True)
    medium = models.TextField(blank=True, null=True)
    modified = models.TextField(blank=True, null=True)
    provenance = models.TextField(blank=True, null=True)
    publisher = models.TextField(blank=True, null=True)
    references = models.TextField(blank=True, null=True)
    relation = models.TextField(blank=True, null=True)
    replaces = models.TextField(blank=True, null=True)
    requires = models.TextField(blank=True, null=True)
    rights = models.TextField(blank=True, null=True)
    rightsHolder = models.TextField(blank=True, null=True)
    source = models.TextField(blank=True, null=True)
    spatial = models.TextField(blank=True, null=True)
    subject = models.TextField(blank=True, null=True)
    tableOfContents = models.TextField(blank=True, null=True)
    temporal = models.TextField(blank=True, null=True)
    title = models.TextField(blank=True, null=True)
    type = models.TextField(blank=True, null=True)
    valid = models.TextField(blank=True, null=True)
    institutionID = models.TextField(blank=True, null=True)
    collectionID = models.TextField(blank=True, null=True)
    datasetID = models.TextField(blank=True, null=True)
    institutionCode = models.TextField(blank=True, null=True)
    collectionCode = models.TextField(blank=True, null=True)
    datasetName = models.TextField(blank=True, null=True)
    ownerInstitutionCode = models.TextField(blank=True, null=True)
    basisOfRecord = models.TextField(blank=True, null=True)
    informationWithheld = models.TextField(blank=True, null=True)
    dataGeneralizations = models.TextField(blank=True, null=True)
    dynamicProperties = models.TextField(blank=True, null=True)
    occurrenceID = models.TextField(blank=True, null=True)
    catalogNumber = models.TextField(blank=True, null=True)
    recordNumber = models.TextField(blank=True, null=True)
    recordedBy = models.TextField(blank=True, null=True)
    individualCount = models.TextField(blank=True, null=True)
    organismQuantity = models.TextField(blank=True, null=True)
    organismQuantityType = models.TextField(blank=True, null=True)
    sex = models.TextField(blank=True, null=True)
    lifeStage = models.TextField(blank=True, null=True)
    reproductiveCondition = models.TextField(blank=True, null=True)
    behavior = models.TextField(blank=True, null=True)
    establishmentMeans = models.TextField(blank=True, null=True)
    occurrenceStatus = models.TextField(blank=True, null=True)
    preparations = models.TextField(blank=True, null=True)
    disposition = models.TextField(blank=True, null=True)
    associatedReferences = models.TextField(blank=True, null=True)
    associatedSequences = models.TextField(blank=True, null=True)
    associatedTaxa = models.TextField(blank=True, null=True)
    otherCatalogNumbers = models.TextField(blank=True, null=True)
    occurrenceRemarks = models.TextField(blank=True, null=True)
    organismID = models.TextField(blank=True, null=True)
    organismName = models.TextField(blank=True, null=True)
    organismScope = models.TextField(blank=True, null=True)
    associatedOccurrences = models.TextField(blank=True, null=True)
    associatedOrganisms = models.TextField(blank=True, null=True)
    previousIdentifications = models.TextField(blank=True, null=True)
    organismRemarks = models.TextField(blank=True, null=True)
    materialSampleID = models.TextField(blank=True, null=True)
    eventID = models.TextField(blank=True, null=True)
    parentEventID = models.TextField(blank=True, null=True)
    fieldNumber = models.TextField(blank=True, null=True)
    eventDate = models.TextField(blank=True, null=True)
    eventTime = models.TextField(blank=True, null=True)
    startDayOfYear = models.BigIntegerField(blank=True, null=True)
    endDayOfYear = models.BigIntegerField(blank=True, null=True)
    year = models.BigIntegerField(blank=True, null=True)
    month = models.BigIntegerField(blank=True, null=True)
    day = models.BigIntegerField(blank=True, null=True)
    verbatimEventDate = models.TextField(blank=True, null=True)
    habitat = models.TextField(blank=True, null=True)
    samplingProtocol = models.TextField(blank=True, null=True)
    samplingEffort = models.TextField(blank=True, null=True)
    sampleSizeValue = models.TextField(blank=True, null=True)
    sampleSizeUnit = models.TextField(blank=True, null=True)
    fieldNotes = models.TextField(blank=True, null=True)
    eventRemarks = models.TextField(blank=True, null=True)
    locationID = models.TextField(blank=True, null=True)
    higherGeographyID = models.TextField(blank=True, null=True)
    higherGeography = models.TextField(blank=True, null=True)
    continent = models.TextField(blank=True, null=True)
    waterBody = models.TextField(blank=True, null=True)
    islandGroup = models.TextField(blank=True, null=True)
    island = models.TextField(blank=True, null=True)
    countryCode = models.TextField(blank=True, null=True)
    stateProvince = models.TextField(blank=True, null=True)
    county = models.TextField(blank=True, null=True)
    municipality = models.TextField(blank=True, null=True)
    locality = models.TextField(blank=True, null=True)
    verbatimLocality = models.TextField(blank=True, null=True)
    verbatimElevation = models.TextField(blank=True, null=True)
    verbatimDepth = models.TextField(blank=True, null=True)
    minimumDistanceAboveSurfaceInMeters = models.TextField(blank=True, null=True)
    maximumDistanceAboveSurfaceInMeters = models.TextField(blank=True, null=True)
    locationAccordingTo = models.TextField(blank=True, null=True)
    locationRemarks = models.TextField(blank=True, null=True)
    decimalLatitude = models.FloatField(blank=True, null=True)
    decimalLongitude = models.FloatField(blank=True, null=True)
    coordinateUncertaintyInMeters = models.FloatField(blank=True, null=True)
    coordinatePrecision = models.TextField(blank=True, null=True)
    pointRadiusSpatialFit = models.TextField(blank=True, null=True)
    verbatimCoordinateSystem = models.TextField(blank=True, null=True)
    verbatimSRS = models.TextField(blank=True, null=True)
    footprintWKT = models.TextField(blank=True, null=True)
    footprintSRS = models.TextField(blank=True, null=True)
    footprintSpatialFit = models.TextField(blank=True, null=True)
    georeferencedBy = models.TextField(blank=True, null=True)
    georeferencedDate = models.TextField(blank=True, null=True)
    georeferenceProtocol = models.TextField(blank=True, null=True)
    georeferenceSources = models.TextField(blank=True, null=True)
    georeferenceVerificationStatus = models.TextField(blank=True, null=True)
    georeferenceRemarks = models.TextField(blank=True, null=True)
    geologicalContextID = models.TextField(blank=True, null=True)
    earliestEonOrLowestEonothem = models.TextField(blank=True, null=True)
    latestEonOrHighestEonothem = models.TextField(blank=True, null=True)
    earliestEraOrLowestErathem = models.TextField(blank=True, null=True)
    latestEraOrHighestErathem = models.TextField(blank=True, null=True)
    earliestPeriodOrLowestSystem = models.TextField(blank=True, null=True)
    latestPeriodOrHighestSystem = models.TextField(blank=True, null=True)
    earliestEpochOrLowestSeries = models.TextField(blank=True, null=True)
    latestEpochOrHighestSeries = models.TextField(blank=True, null=True)
    earliestAgeOrLowestStage = models.TextField(blank=True, null=True)
    latestAgeOrHighestStage = models.TextField(blank=True, null=True)
    lowestBiostratigraphicZone = models.TextField(blank=True, null=True)

SysIMiBio/sndb/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render
from djgeojson.views import GeoJSONLayerView

from .models import Occurrences


@login_required
def occs_list(request):
    template_name = 'occs_list.html'
    objects = Occurrences.objects.only(
        'scientificName', 'family', 'hasCoordinate',
        'county', 'taxonRank', 'municipality', 'locality'
    ).filter(stateProvince__icontains='siones',
             decimalLatitude__isnull=False,
             decimalLongitude__isnull=False
             )[0:100]
    paginator = Paginator(objects, 25)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'object_list': objects,
        'page_obj': page_obj,
    }
    return render(request, template_name, context)


@login_required
def occ_detail(request, pk):
    template_name = 'occs_details.html'
    occ = Occurrences.objects.get(pk=pk)
    context = {
        'occ_detail': occ,
    }
    return render(request, template_name, context)


@login_required
def occs_map(request):
    occsHeat = Occurrences.objects.filter(
        stateProvince__icontains='iones',
        decimalLatitude__isnull=False,
        decimalLongitude__isnull=False
    )[0:100]
    context = {
        'occs': occsHeat,
    }
    return render(request, 'occs_mapSNDB.html', context)


class OccurrencesGeoJson(GeoJSONLayerView):
    model = Occurrences
    properties = ('popup_content',)

    def get_queryset(self):
        context = Occurrences.objects.filter(
        stateProvince__icontains='iones',
        decimalLatitude__isnull=False,
        decimalLongitude__isnull=False
    ).extra(select={'geom': 'geom_original'})[0:100]
        return context


occs_geojson = OccurrencesGeoJson.as_view()


def occs(request):
    occsHeat = Occurrences.objects.filter(
        stateProvince__icontains='iones',
        decimalLatitude__isnull=False,
        decimalLongitude__isnull=False
    )
    context = {
        'occs': occsHeat,
    }
    return render(request, 'occs_js.html', context)

SysIMiBio/sndb/templates/mapaSNDB.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'libs/leaflet/leaflet.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
    <div id="map">
    </div>
    <input type="hidden" id="occs_geojson" value="{% url 'sndb:occs_geojson' %}">
    <input type="hidden" id="occsCoord" value="{% url 'sndb:occsList' %}">
{% endblock content %}

{% block js %}
    <script src="{% static 'libs/leaflet/leaflet.js' %}"></script>
    <script src="{% static 'libs/leaflet-heat/leaflet-heat.js' %}"></script>
    <script src="{% url 'sndb:occsList' %}"></script>
    <script src="{% static 'js/map.js' %}"></script>
{% endblock js %}

SysIMiBio/sndb/templates/occs_details.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link href="{% static 'libs/leaflet/leaflet.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}

<a href="{% url 'sndb:occs_list' %}"> voltar </a>

<h1>Detalles de la ocorrencia: {{ occ_detail.scientificName }}</h1>
<strong>id: {{ occ_detail.pk }}</strong>
<div class="row">
<div class="col-sm-4">
    <table class = "table table-user-information">
        <tbody>
        <tr>

            <th class="text-right">Nombre scientifico</th>
            <td>{{ occ_detail.scientificName }}</td>
        </tr>

            <th class="text-right">Id de la Ocurencia</th>
            <td>{{ occ_detail.occurrenceID }}</td>
        </tr>

            <th class="text-right">Modificado</th>
            <td>{{ occ_detail.modified }}</td>
        </tr>

            <th class="text-right">Basis of record</th>
            <td>{{ occ_detail.basisOfRecord }}</td>
        </tr>

            <th class="text-right">ID Institución</th>
            <td>{{ occ_detail.institutionCode }}</td>
        </tr>

            <th class="text-right">ID Colección</th>
            <td>{{ occ_detail.collectionCode }}</td>
        </tr>

            <th class="text-right">ID Catálogo</th>
            <td>{{ occ_detail.catalogNumber }}</td>
        </tr>

            <th class="text-right">Reino</th>
            <td>{{ occ_detail.kingdom }}</td>
        </tr>

            <th class="text-right">Phylum</th>
            <td>{{ occ_detail.phylum }}</td>
        </tr>

            <th class="text-right">Clase</th>
            <td>{{ occ_detail.clase }}</td>
        </tr>

            <th class="text-right">Orden</th>
            <td>{{ occ_detail.order }}</td>
        </tr>

            <th class="text-right">Familia</th>
            <td>{{ occ_detail.family }}</td>
        </tr>

            <th class="text-right">Genero</th>
            <td>{{ occ_detail.genus }}</td>
        </tr>

            <th class="text-right">Epíteto</th>
            <td>{{ occ_detail.specificEpithet }}</td>
        </tr>

            <th class="text-right">Epíteto infraespecífico</th>
            <td>{{ occ_detail.infraspecificEpithet }}</td>
        </tr>

            <th class="text-right">Taxon rank</th>
            <td>{{ occ_detail.taxonRank }}</td>
        </tr>

            <th class="text-right">Autor del nombre científico y año de publicación</th>
            <td>{{ occ_detail.scientificNameAuthorship }}</td>
        </tr>

            <th class="text-right">Calificador de la identificación</th>
            <td>{{ occ_detail.identificationQualifier }}</td>
        </tr>

            <th class="text-right">Colector</th>
            <td>{{ occ_detail.recordedBy }}</td>
        </tr>

            <th class="text-right">Número de registro del colector</th>
            <td>{{ occ_detail.recordNumber }}</td>
        </tr>

            <th class="text-right">Departamento</th>
            <td>{{ occ_detail.county }}</td>
        </tr>

            <th class="text-right">Provincia o Estado</th>
            <td>{{ occ_detail.stateProvince }}</td>
        </tr>

            <th class="text-right">Municipalidad</th>
            <td>{{ occ_detail.municipality }}</td>
        </tr>

            <th class="text-right">Localidad</th>
            <td>{{ occ_detail.localilty }}</td>
        </tr>

            <th class="text-right">Longitude</th>
            <td>{{ occ_detail.decimalLongitude }}</td>
        </tr>

            <th class="text-right">Latitude</th>
            <td>{{ occ_detail.decimalLatitude }}</td>
        </tr>

            <th class="text-right">Incertidunbre de las coordenadas</th>
            <td>{{ occ_detail.coordinateUncartaintyInMeters }}</td>
        </tr>

            <th class="text-right">Protocolo de georeferenciación</th>
            <td>{{ occ_detail.georeferenceProtocol }}</td>
        </tr>

            <th class="text-right">Fuentes de georeferenciación</th>
            <td>{{ occ_detail.georeferenceSources }}</td>
        </tr>

        </tbody>
    </table>
</div>


    {% if occ_detail.geom_original %}
    <div class="col-sm-8">
        <input type="hidden" id="y_cen" value="{{ occ_detail.geom_original.y|safe }}">
        <input type="hidden" id="x_cen" value="{{ occ_detail.geom_original.x|safe }}">
        <div id="map-detail"></div>
    </div>
    {% endif %}

</div>
{% endblock content %}
{% block js %}
    <script src="{% static 'libs/leaflet/leaflet.js' %}"></script>

    <script>
        var y_cen = $("#y_cen").val();
        var x_cen = $("#x_cen").val();

        var gstreets = L.tileLayer('http://www.google.cn/maps/vt?lyrs=m@189&gl=cn&x={x}&y={y}&z={z}', {
            maxZoom: 20,
            attribution: 'google'
        });

        var satellite = L.tileLayer('http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}', {
        maxZoom: 20,
        attribution: 'google'});

        var occ = L.marker([y_cen, x_cen]);

        var map = L.map('map-detail', {
            center: [y_cen, x_cen],
            zoom: 9,
            layers: [gstreets, satellite, occ],
        });

        var baseLayers = {
            "Google Streets": gstreets, satellite,
        };

        var overlays = {
            "Ocorrencia": occ,
        };

        var control = L.control.layers(baseLayers, overlays).addTo(map);

    </script>

{% endblock js %}

SysIMiBio/sndb/templates/occs_js.html
var heatCoords = [
{% for occ in occs %}
    {% if occ.geom_original %}
        [{{ occ.geom_original.y|safe }}, {{ occ.geom_original.x|safe }}, 1],
    {% endif %}
{% endfor %}
];

SysIMiBio/sndb/templates/occs_list.html
{% extends "base.html" %}

{% block content %}
<div class="col-md-8">
    {% if user.is_authenticated %}
        <h2><i class ="fa fa-pagelines"></i> Lista biodiversidad</h2>
        {% if object_list %}
            <table class = 'table table-striped'>
                <thead>
                <tr>
                    <th>Nombre scientifico</th>
                    <th>Familia</th>
                    <th>Posee coordenadas?</th>
                    <th>Departamento</th>
                    <th>Taxon rank</th>
                    <th>Municipalidad</th>
                    <th>Localidad</th>
                </tr>
                </thead>

                {% for object in page_obj %}
                <tr>
                    <td>
                        <a href="{{ object.get_absolute_url }}">{{ object.scientificName }}</a>
                    </td>
                    <td>{{ object.Family }}</td>
                    <td>{{ object.hasCoordinate }}</td>
                    <td>{{ object.county }}</td>
                    <td>{{ object.taxonRank }}</td>
                    <td>{{ object.municipality }}</td>
                    <td>{{ object.locality }}</td>
                </tr>
                {% endfor %}
            </table>

    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item disabled">
                    <li class="page-item"><a class="page-link" href="?page=1"> Início</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"> {{ page_obj.previous_page_number }} </a></li>
            {% endif %}
            <span class="current">
                <li class="page-item active">
                  <a class="page-link" href="#"> {{ page_obj.number }} <span class="sr-only">(current)</span></a>
                </li>
            </span>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"> {{ page_obj.next_page_number }} </a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"> Ultimo </a></li>
            {% endif %}
        </ul>
    </nav>
        {% else %}
            <p class="alert alert-warning">
            <i class="fa fa-warning"></i> Base de datos sin registros!</p>
        {% endif %}
</div>

    {% else %}
        <div class="alert alert-danger" role="alert">
            Acceso negado. Logar o crear usuário.
        </div>
    {% endif %}

{% endblock content %}

SysIMiBio/sndb/templates/occs_mapSNDB.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'libs/leaflet/leaflet.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
    <h1>

    </h1>

    {% if user.is_authenticated %}
        <div class="alert alert-danger" role="alert">
            Por cuestiones de desarrollo, se presentan solamente 100 ocurrencias y no su totalidad.
        </div>
        <div id="map">
        </div>
        <input type="hidden" id="occs_geojson" value="{% url 'sndb:occs_geojson' %}">
    {% else %}
        <div class="alert alert-danger" role="alert">
            Acceso negado. Logar o crear usuário.
        </div>
    {% endif %}
{% endblock content %}

{% block js %}
    <script>
        var heatCoords = [
            {% for occ in occs %}
                {% if occ.geom_original %}
                    [{{ occ.geom_original.y|safe }}, {{ occ.geom_original.x|safe }}, 1],
                {% endif %}
            {% endfor %}
        ];
    </script>
    <script type="application/javascript" src="{% static 'libs/leaflet/leaflet.js' %}"></script>
    <script type="application/javascript" src="{% static 'libs/leaflet-heat/leaflet-heat.js' %}"></script>
    <script type="application/javascript" src="{% static 'js/map.js' %}"></script>
{% endblock js %}

SysIMiBio/sndb/templates/species_list.html
{% extends "base.html" %}

{% block content %}
    <h2><i class ="fa fa-pagelines"></i> Lista biodiversidad</h2>
    {% if object_list %}
        <table class = 'table table-striped'>
            <thead>
            <tr>
                <th>Nombre scientifico</th>
                <th>Familia</th>
                <th>Posee coordenadas?</th>
                <th>Departamento</th>
                <th>Municipalidad</th>
                <th>Localidad</th>
            </tr>
            </thead>

            {% for object in page_obj %}
            <tr>
                <td>{{ object.scientificName }}</td>
                <td>{{ object.Family }}</td>
                <td>{{ object.hasCoordinate }}</td>
                <td>{{ object.county }}</td>
                <td>{{ object.municipality }}</td>
                <td>{{ object.localilty }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <p class="alert alert-warning">
            <i class="fa fa-warning"></i> Base de datos sin registros!</p>
    {% endif %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; início </a>
            <a href="?page={{ page_obj.previous_page_number }}"> anterior </a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"> próximo </a>
            <a href="?page={{ page_obj.paginator.num_pages }}"> último  &raquo;</a>
        {% endif %}
        </span>
</div>

{% endblock content %}